services:
  app1:
    build: ./myapp1
    ports:
      - 5001:5000
  app2:
    build: ./myapp2
    ports:
      - 5002:5000
  ngnix:
    build: ./ngnix
    ports:
      - 8080:80
    depends_on:
      - app1
      - app2
